### ISSUE TITLE
jenkins setup wizard

### ISSUE THREAD

**Issue by sandeep5683** [QT-DevOps/AzureIssues#2]
hi , i create aws instance after that set up the java ubuntu 18.04 as well as setup the jenkins on ubuntu. i am trying setup wizard jenkins but i dint get unlock jenkins page instead of that i got jenkins sign in page, please let me know how to sort out this issue. ( i deleted the jenkins home directory also in users)

**Comment by bhaskardegala** [comment]
I think your Jenkins directory in Linux probably be in /var/lib/Jenkins ( to know the exact location first become root user then switch to Jenkins user (as we don't know the password of it) then just type pwd you will come to know the exact location) then delete the folder this will help you in resolving the sign-in issue

**Comment by sandeep5683** [comment]
> /var/lib/Jenkins
thanks buddy can you guide me how to do it  that process, i am new to this environment

**Comment by bhaskardegala** [comment]
> > /var/lib/Jenkins
> > thanks buddy can you guide me how to do it  that process, i am new to this environment

just follow the commands 
first log on to your machine
then type "sudo -i" this will make you root user
then switch to jenkins user by " su jenkins "
pwd this gives you your present working directory
then get to that directory using cd command and then delete jenkins folder using "rm -r /path/jenkins " replace path with your path then start woking again
in order to run some commands you need to give jenkins sudo permissions for that execute following command visudo and the line " jenkins ALL=(ALL:ALL) NOPASSWD:ALL "save and close it

**Comment by bhaskardegala** [comment]
Hey Sandeep
If your issue was resolved please close the issue

**Comment by sandeep5683** [comment]
thanks to all
