### ISSUE TITLE
Issue while creating VM in AZURE

### ISSUE THREAD

**Issue by AravindBabuS** [QT-DevOps/AzureIssues#61]
While creating the VM, in Select VM Size page all the VMs details are grayed out and couldn’t select any VM from the list. (The current subscription I have is Free Trail and not allowing to select Pay as our go) 
Attaching the screen print for reference
[VM Size Selection issue.docx](https://github.com/QT-DevOps/AzureIssues/files/4474261/VM.Size.Selection.issue.docx)

**Comment by NareshAbbanapuri** [comment]
hi
please upgrade your subscription (pay as you go)
you will get you're credits

**Comment by srmanikanta** [comment]
This happen in two cases 
first one is your free trail subscription is over then you face this issue. so if your issue is related to this please upgrade this subscription to pay as you go.
second one resource quota limit if your resource quota limit exceeds. there might be a chance to get this error.so your error is related to this increase the service quota and try again
to do that contact azure help+support, raise a case over there then give a clarity what exactly is. 
or select another region and try to create the vm's.

**Comment by shaikkhajaibrahim** [comment]
https://azure.microsoft.com/en-us/blog/our-commitment-to-customers-and-microsoft-cloud-services-continuity/
