### ISSUE TITLE
i need some help in fixing this error while bootstraping

### ISSUE THREAD

**Issue by Teja1213** [QT-DevOps/AzureIssues#69]
![bootstrap error](https://user-images.githubusercontent.com/26798087/79631127-fbb57380-8124-11ea-931b-3323c4a1f901.png)

**Comment by srmanikanta** [comment]
Hi teja,
This repository is for azure issues not for devops if you have any issues related to devops please raise an concern issue in devops issues repository.
and solution for your issue is 
mention your pem file related to your machine and copy that  pemfile to che-repo
execute the bootstrap command in chef-repo  
`this error belong to a wrong command name type like this knife bootstrap not kinfe`
please close the issue.
