### ISSUE TITLE
Inbound security rule

### ISSUE THREAD

**Issue by shravanpragallapati** [QT-DevOps/AzureIssues#83]
Why are we changing the priority in Inbound security rule, What is the role of it

**Comment by srmanikanta** [comment]
hi shravanpragallapati, for example you have two rules in your network security group for the same purpose  ,one for allow and another rule for deny. In this case you are write the two rules one after another, which rule means allow rule/deny write the first that rule will be applied, that is why  we give the priority in the rules because `lower the number is highest priority`
if it is useful please close the issue.

**Comment by shravanpragallapati** [comment]
Thank you mani
