### ISSUE TITLE
Issue while doing Test kitchen setup with AWS.

### ISSUE THREAD

**Issue by SBqt** [QT-DevOps/AzureIssues#98]
I created a cookbook using chef generate cookbook -b kitchenawsdemo. I got the following errors but eventually cookbook was created in the folder but then i used to type aws configure, the first step towards setting test kitchen, ita not working. 
Please help me how to overcome this issue.
![Capture4](https://user-images.githubusercontent.com/71276753/93106917-8dbea980-f6ce-11ea-9104-73d876b831be.JPG)
![Capture1](https://user-images.githubusercontent.com/71276753/93106924-8f886d00-f6ce-11ea-8ac8-89128a759add.JPG)
![Capture2](https://user-images.githubusercontent.com/71276753/93106928-90210380-f6ce-11ea-9f5a-484666164691.JPG)
![Capture3](https://user-images.githubusercontent.com/71276753/93106931-91523080-f6ce-11ea-98b0-424e68a332da.JPG)

**Comment by srmanikanta** [comment]
hi execute the below steps manually in your chef node because you are trying to run git commit but before git commit it is mandatory ti configure the user and the mail
git config --global user.name `<yourname>`
git config --global user.email `<youremail>`
once you execute those two commands then try to execute the cookbook.

**Comment by shaikkhajaibrahim** [comment]
This is not the right page for AWS Issues
